<a href="https://colab.research.google.com/github/AndraSatria2018/Data-Mining/blob/main/Preprocessing_(Andra_11194).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tugas 3 Mata Kuliah Data Mining ( PreProcessing data )

data yang digunakan adalah data Siswa

In [79]:
import numpy as np
import matplotlib.pyplot as ply
import pandas as pd

In [80]:
dataset = pd.read_csv('buku.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

In [ ]:
print(y)

In [82]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') 
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [83]:
print(x)

[['Andra' 167.0 60.0]
 ['Satria' 168.0 62.0]
 ['Hermawan' 169.0 59.375]
 ['Andra' 160.0 59.0]
 ['Ari' 155.0 49.0]
 ['Hermawan' 168.0 45.0]
 ['Danu' 178.0 68.0]
 ['Satria' 168.0 72.0]
 ['Eri' 185.0 59.375]
 ['Andra' 162.0 60.0]]


In [84]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [85]:
print(x)

[[1.0 0.0 0.0 0.0 0.0 0.0 167.0 60.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 168.0 62.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 169.0 59.375]
 [1.0 0.0 0.0 0.0 0.0 0.0 160.0 59.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 155.0 49.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 168.0 45.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 178.0 68.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 168.0 72.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 185.0 59.375]
 [1.0 0.0 0.0 0.0 0.0 0.0 162.0 60.0]]


In [86]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [87]:
print(y)

[1 0 0 1 1 1 0 1 0 0]


In [88]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [89]:
print(x_train)

[[0.0 0.0 1.0 0.0 0.0 0.0 178.0 68.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 155.0 49.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 167.0 60.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 160.0 59.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 168.0 62.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 168.0 72.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 185.0 59.375]
 [0.0 0.0 0.0 0.0 1.0 0.0 168.0 45.0]]


In [90]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 0.0 169.0 59.375]
 [1.0 0.0 0.0 0.0 0.0 0.0 162.0 60.0]]


In [91]:
print(y_train)

[0 1 1 1 0 1 0 1]


In [92]:
print(y_test)

[0 0]


In [94]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [95]:
print(x_train)

[[0.0 0.0 1.0 -0.3779644730092272 -0.3779644730092272 -0.5773502691896258
  1.0650358071057624 1.0444878189374986]
 [0.0 1.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.5773502691896258
  -1.5478520396603748 -1.235758478778836]
 [1.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.5773502691896258
  -0.18460620656499882 0.08438411463588412]
 [1.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 -0.5773502691896258
  -0.9798329425373015 -0.0356288484018177]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 1.7320508075688774
  -0.07100238714038416 0.32441004071128776]
 [0.0 0.0 0.0 -0.3779644730092272 -0.3779644730092272 1.7320508075688774
  -0.07100238714038416 1.524539671088306]
 [0.0 0.0 0.0 2.6457513110645907 -0.3779644730092272 -0.5773502691896258
  1.8602625430780653 0.009376012737320484]
 [0.0 0.0 0.0 -0.3779644730092272 2.6457513110645907 -0.5773502691896258
  -0.07100238714038416 -1.7158103309296433]]


In [96]:
print(x_test)

[[0.0 0.0 0.0 4.1633363423443376e-17 1.0000000000000002
  2.7755575615628914e-17 169.0 59.375]
 [1.0 0.0 0.0 4.1633363423443376e-17 5.551115123125784e-17
  2.7755575615628914e-17 162.0 60.0]]
